EB-1200: Implement signals in live preview sdk
contentstack/live-preview-sdk pull request #111
Opened 2024-03-11 12:53 UTC by Vishvam10

### Jira Story

Work has been completed on this Jira story : https://contentstack.atlassian.net/browse/EB-1200

### Overview

This PR focuses on integrating `DeepSignal` package into existing codebase and refactoring the `Config` object to make it reactive. This will make things easier in the future (say if we want to subscribe to a property, etc) and also improves the DX.

### Changes Made

- Installed and configured `DeepSignal` package, a re-implementation of `Preact Signals` using `JS Proxies`
- Updated all the static methods of the `Config` object
- Refactored **all** Config related code to incorporate `DeepSignal`
- Re-wrote and corrected broken test cases related to the `Config` object

2024-03-11 15:53 UTC, Deepak-Kharah requested changes

2024-03-11 15:53 UTC, Deepak-Kharah commented on src/configManager/__test__/handleUserConfig.test.ts
Test cases are missing

2024-03-11 15:53 UTC, Deepak-Kharah commented on src/livePreview/editButton/editButton.ts
> +                editButton.position as unknown as string
Let's remove all the as unknown code

2024-03-12 05:01 UTC, Vishvam10 commented on src/livePreview/eventManager/postMessageEvent.hooks.ts
> +                onChange!();
Hmm. Not really. I'll remove it

2024-03-12 05:47 UTC, Deepak-Kharah requested changes

2024-03-12 05:47 UTC, Deepak-Kharah commented on src/livePreview/editButton/editButton.ts
> +    console.log('[IN SDK] : WINDOWTYPE : ', Config.get().windowType);
remove the logs

2024-03-12 06:11 UTC, Deepak-Kharah approved these changes

2024-03-12 06:16 UTC, merged