Ve 2173 - variant support in data-cslp
contentstack/live-preview-sdk pull request #200
Opened 2024-08-26 05:59 UTC by KANE-99

2024-08-26 06:35 UTC, alt-test approved these changes
looks good!

2024-08-26 06:35 UTC, alt-test commented on src/live-preview.ts
> +            console.log("🚀 ~ LivePreview ~ scrollHandler ~ variant:", variant);
Let's remove this log

2024-08-26 06:35 UTC, alt-test commented on src/live-preview.ts
> +                    console.log(
Remove the logs

2024-08-26 06:37 UTC, Deepak-Kharah requested changes
Let's remove the logs

2024-08-26 06:37 UTC, Deepak-Kharah commented on src/live-preview.ts
> +            console.log("🚀 ~ LivePreview ~ scrollHandler ~ variant:", variant);
let's remove the logs

2024-08-26 06:37 UTC, Deepak-Kharah commented on src/live-preview.ts
> +                    console.log(
Let's remove the logs

2024-08-26 07:08 UTC, Deepak-Kharah approved these changes
Looks good!

2024-08-27 07:11 UTC, KANE-99 commented on src/__test__/live-preview.test.ts
> +        variantTitlePara.setAttribute("data-test-id", "title-variant-para");
change it to `title-variant-heading`

2024-08-28 06:34 UTC, closed without merging